version: "2.1"

services:
  mysql:
    image: mysql:5.5
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PM-Testdb
    container_name: pm200-db

  processmaker:
    depends_on:
      - mysql
    image: devopsstacks/pm:200
    ports:
      - 80:80
      - 443:443
    restart: always
    container_name: pm200-app
    environment:
      PM_URL: https://ufpr.dl.sourceforge.net/project/processmaker/ProcessMaker/3.0.1.8/processmaker-3.0.1.8-community.tar.gz

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: pm200-phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    environment:
      PMA_HOST: mysql