version: "2.1"

services:
  mysql:
    image: mysql:5.5
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PM-Testdb
    container_name: pm205-db

  processmaker:
    depends_on:
      - mysql
    image: devopsstacks/pm:205
    ports:
      - 80:80
      - 443:443
    restart: always
    container_name: pm205-app
    environment:
      PM_URL:  http://bitnami.processmaker.com/official/processmaker-3.2.1.tar.gz

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: pm205-phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    environment:
      PMA_HOST: mysql