version: "2.1"

services:
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PM-Testdb
    container_name: pm225-db

  processmaker:
    depends_on:
      - mysql
    image: devopsstacks/pm:225
    ports:
      - 80:80
      - 443:443
    restart: always
    container_name: pm225-app
    environment:
      PM_URL: artifacts.processmaker.net/generic/processmaker-3.3.0-build10.tar.gz

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: pm225-phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    environment:
      PMA_HOST: mysql