version: "2.1"

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PM-Testdb
    container_name: pm255-db
    command: 
      --optimizer-switch="derived_merge=off"
      --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

  processmaker:
    depends_on:
      - mysql
    image: devopsstacks/pm:225
      - 80:80
      - 443:443
    restart: always
    container_name: pm255-app
    environment:
      PM_URL: artifacts.processmaker.net/generic/processmaker-3.3.0-build10.tar.gz

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: pm255-phpmyadmin
    restart: always
    ports:
     - 8080:80
    environment:
      PMA_HOST: mysql
