version: "2.1"

services:
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PM-Testdb
    container_name: pmN220-db

  processmaker:
    depends_on:
      - mysql
    image: stack-n220:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    container_name: pmN220-app
    environment:
      PM_URL: artifacts.processmaker.net/official/processmaker-3.2.2+001.tar.gz

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: pmN220-phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    environment:
      PMA_HOST: mysql